/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.notifications.model;

import java.util.Objects;
import com.finbourne.notifications.model.AttemptStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.notifications.JSON;

/**
 * Details of an attempt of delivery.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Attempt {
  public static final String SERIALIZED_NAME_ATTEMPT_NUMBER = "attemptNumber";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_NUMBER)
  private Integer attemptNumber;

  public static final String SERIALIZED_NAME_ATTEMPT_TIME = "attemptTime";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_TIME)
  private OffsetDateTime attemptTime;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private AttemptStatus status;

  public Attempt() {
  }

  public Attempt attemptNumber(Integer attemptNumber) {
    
    this.attemptNumber = attemptNumber;
    return this;
  }

   /**
   * The attempt number of the delivery.
   * @return attemptNumber
  **/
  @jakarta.annotation.Nonnull
  public Integer getAttemptNumber() {
    return attemptNumber;
  }


  public void setAttemptNumber(Integer attemptNumber) {
    this.attemptNumber = attemptNumber;
  }


  public Attempt attemptTime(OffsetDateTime attemptTime) {
    
    this.attemptTime = attemptTime;
    return this;
  }

   /**
   * The time that the delivery was attempted.
   * @return attemptTime
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getAttemptTime() {
    return attemptTime;
  }


  public void setAttemptTime(OffsetDateTime attemptTime) {
    this.attemptTime = attemptTime;
  }


  public Attempt status(AttemptStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nonnull
  public AttemptStatus getStatus() {
    return status;
  }


  public void setStatus(AttemptStatus status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attempt attempt = (Attempt) o;
    return Objects.equals(this.attemptNumber, attempt.attemptNumber) &&
        Objects.equals(this.attemptTime, attempt.attemptTime) &&
        Objects.equals(this.status, attempt.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attemptNumber, attemptTime, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attempt {\n");
    sb.append("    attemptNumber: ").append(toIndentedString(attemptNumber)).append("\n");
    sb.append("    attemptTime: ").append(toIndentedString(attemptTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attemptNumber");
    openapiFields.add("attemptTime");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("attemptNumber");
    openapiRequiredFields.add("attemptTime");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Attempt
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Attempt.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Attempt is not found in the empty JSON string", Attempt.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Attempt.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `status`
      AttemptStatus.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Attempt.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Attempt' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Attempt> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Attempt.class));

       return (TypeAdapter<T>) new TypeAdapter<Attempt>() {
           @Override
           public void write(JsonWriter out, Attempt value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Attempt read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Attempt given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Attempt
  * @throws IOException if the JSON string is invalid with respect to Attempt
  */
  public static Attempt fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Attempt.class);
  }

 /**
  * Convert an instance of Attempt to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
