/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.notifications.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.notifications.JSON;

/**
 * Holds readonly information about an Azure Service Bus notification
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AzureServiceBusTypeResponse {
  /**
   * The type of delivery mechanism for this notification
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    AZURESERVICEBUS("AzureServiceBus");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_NAMESPACE_REF = "namespaceRef";
  @SerializedName(SERIALIZED_NAME_NAMESPACE_REF)
  private String namespaceRef;

  public static final String SERIALIZED_NAME_QUEUE_NAME_REF = "queueNameRef";
  @SerializedName(SERIALIZED_NAME_QUEUE_NAME_REF)
  private String queueNameRef;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_TENANT_ID_REF = "tenantIdRef";
  @SerializedName(SERIALIZED_NAME_TENANT_ID_REF)
  private String tenantIdRef;

  public static final String SERIALIZED_NAME_CLIENT_ID_REF = "clientIdRef";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID_REF)
  private String clientIdRef;

  public static final String SERIALIZED_NAME_CLIENT_SECRET_REF = "clientSecretRef";
  @SerializedName(SERIALIZED_NAME_CLIENT_SECRET_REF)
  private String clientSecretRef;

  public AzureServiceBusTypeResponse() {
  }

  public AzureServiceBusTypeResponse type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of delivery mechanism for this notification
   * @return type
  **/
  @jakarta.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public AzureServiceBusTypeResponse namespaceRef(String namespaceRef) {
    
    this.namespaceRef = namespaceRef;
    return this;
  }

   /**
   * Reference to namespace from Configuration Store
   * @return namespaceRef
  **/
  @jakarta.annotation.Nullable
  public String getNamespaceRef() {
    return namespaceRef;
  }


  public void setNamespaceRef(String namespaceRef) {
    this.namespaceRef = namespaceRef;
  }


  public AzureServiceBusTypeResponse queueNameRef(String queueNameRef) {
    
    this.queueNameRef = queueNameRef;
    return this;
  }

   /**
   * Reference to queue name from Configuration Store
   * @return queueNameRef
  **/
  @jakarta.annotation.Nullable
  public String getQueueNameRef() {
    return queueNameRef;
  }


  public void setQueueNameRef(String queueNameRef) {
    this.queueNameRef = queueNameRef;
  }


  public AzureServiceBusTypeResponse body(String body) {
    
    this.body = body;
    return this;
  }

   /**
   * The body of the Azure service bus Message
   * @return body
  **/
  @jakarta.annotation.Nullable
  public String getBody() {
    return body;
  }


  public void setBody(String body) {
    this.body = body;
  }


  public AzureServiceBusTypeResponse tenantIdRef(String tenantIdRef) {
    
    this.tenantIdRef = tenantIdRef;
    return this;
  }

   /**
   * Reference to tenant id from Configuration Store
   * @return tenantIdRef
  **/
  @jakarta.annotation.Nullable
  public String getTenantIdRef() {
    return tenantIdRef;
  }


  public void setTenantIdRef(String tenantIdRef) {
    this.tenantIdRef = tenantIdRef;
  }


  public AzureServiceBusTypeResponse clientIdRef(String clientIdRef) {
    
    this.clientIdRef = clientIdRef;
    return this;
  }

   /**
   * Reference to client id from Configuration Store
   * @return clientIdRef
  **/
  @jakarta.annotation.Nullable
  public String getClientIdRef() {
    return clientIdRef;
  }


  public void setClientIdRef(String clientIdRef) {
    this.clientIdRef = clientIdRef;
  }


  public AzureServiceBusTypeResponse clientSecretRef(String clientSecretRef) {
    
    this.clientSecretRef = clientSecretRef;
    return this;
  }

   /**
   * Reference to client secret from Configuration Store
   * @return clientSecretRef
  **/
  @jakarta.annotation.Nullable
  public String getClientSecretRef() {
    return clientSecretRef;
  }


  public void setClientSecretRef(String clientSecretRef) {
    this.clientSecretRef = clientSecretRef;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AzureServiceBusTypeResponse azureServiceBusTypeResponse = (AzureServiceBusTypeResponse) o;
    return Objects.equals(this.type, azureServiceBusTypeResponse.type) &&
        Objects.equals(this.namespaceRef, azureServiceBusTypeResponse.namespaceRef) &&
        Objects.equals(this.queueNameRef, azureServiceBusTypeResponse.queueNameRef) &&
        Objects.equals(this.body, azureServiceBusTypeResponse.body) &&
        Objects.equals(this.tenantIdRef, azureServiceBusTypeResponse.tenantIdRef) &&
        Objects.equals(this.clientIdRef, azureServiceBusTypeResponse.clientIdRef) &&
        Objects.equals(this.clientSecretRef, azureServiceBusTypeResponse.clientSecretRef);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, namespaceRef, queueNameRef, body, tenantIdRef, clientIdRef, clientSecretRef);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AzureServiceBusTypeResponse {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    namespaceRef: ").append(toIndentedString(namespaceRef)).append("\n");
    sb.append("    queueNameRef: ").append(toIndentedString(queueNameRef)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    tenantIdRef: ").append(toIndentedString(tenantIdRef)).append("\n");
    sb.append("    clientIdRef: ").append(toIndentedString(clientIdRef)).append("\n");
    sb.append("    clientSecretRef: ").append(toIndentedString(clientSecretRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("namespaceRef");
    openapiFields.add("queueNameRef");
    openapiFields.add("body");
    openapiFields.add("tenantIdRef");
    openapiFields.add("clientIdRef");
    openapiFields.add("clientSecretRef");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AzureServiceBusTypeResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AzureServiceBusTypeResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AzureServiceBusTypeResponse is not found in the empty JSON string", AzureServiceBusTypeResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("namespaceRef") != null && !jsonObj.get("namespaceRef").isJsonNull()) && !jsonObj.get("namespaceRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `namespaceRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("namespaceRef").toString()));
      }
      if ((jsonObj.get("queueNameRef") != null && !jsonObj.get("queueNameRef").isJsonNull()) && !jsonObj.get("queueNameRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queueNameRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queueNameRef").toString()));
      }
      if ((jsonObj.get("body") != null && !jsonObj.get("body").isJsonNull()) && !jsonObj.get("body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
      if ((jsonObj.get("tenantIdRef") != null && !jsonObj.get("tenantIdRef").isJsonNull()) && !jsonObj.get("tenantIdRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantIdRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantIdRef").toString()));
      }
      if ((jsonObj.get("clientIdRef") != null && !jsonObj.get("clientIdRef").isJsonNull()) && !jsonObj.get("clientIdRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientIdRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientIdRef").toString()));
      }
      if ((jsonObj.get("clientSecretRef") != null && !jsonObj.get("clientSecretRef").isJsonNull()) && !jsonObj.get("clientSecretRef").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientSecretRef` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientSecretRef").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AzureServiceBusTypeResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AzureServiceBusTypeResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AzureServiceBusTypeResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AzureServiceBusTypeResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<AzureServiceBusTypeResponse>() {
           @Override
           public void write(JsonWriter out, AzureServiceBusTypeResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AzureServiceBusTypeResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AzureServiceBusTypeResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AzureServiceBusTypeResponse
  * @throws IOException if the JSON string is invalid with respect to AzureServiceBusTypeResponse
  */
  public static AzureServiceBusTypeResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AzureServiceBusTypeResponse.class);
  }

 /**
  * Convert an instance of AzureServiceBusTypeResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
