/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.notifications.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.notifications.JSON;

/**
 * The information required to create or update an Email notification
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EmailNotificationType {
  /**
   * The type of delivery mechanism for this notification
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    EMAIL("Email");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public static final String SERIALIZED_NAME_PLAIN_TEXT_BODY = "plainTextBody";
  @SerializedName(SERIALIZED_NAME_PLAIN_TEXT_BODY)
  private String plainTextBody;

  public static final String SERIALIZED_NAME_HTML_BODY = "htmlBody";
  @SerializedName(SERIALIZED_NAME_HTML_BODY)
  private String htmlBody;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS_TO = "emailAddressTo";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS_TO)
  private List<String> emailAddressTo = new ArrayList<>();

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS_CC = "emailAddressCc";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS_CC)
  private List<String> emailAddressCc;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS_BCC = "emailAddressBcc";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS_BCC)
  private List<String> emailAddressBcc;

  public EmailNotificationType() {
  }

  public EmailNotificationType type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of delivery mechanism for this notification
   * @return type
  **/
  @jakarta.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public EmailNotificationType subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * The subject of the email
   * @return subject
  **/
  @jakarta.annotation.Nonnull
  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public EmailNotificationType plainTextBody(String plainTextBody) {
    
    this.plainTextBody = plainTextBody;
    return this;
  }

   /**
   * The plain text body of the email
   * @return plainTextBody
  **/
  @jakarta.annotation.Nonnull
  public String getPlainTextBody() {
    return plainTextBody;
  }


  public void setPlainTextBody(String plainTextBody) {
    this.plainTextBody = plainTextBody;
  }


  public EmailNotificationType htmlBody(String htmlBody) {
    
    this.htmlBody = htmlBody;
    return this;
  }

   /**
   * The HTML body of the email (if any)
   * @return htmlBody
  **/
  @jakarta.annotation.Nullable
  public String getHtmlBody() {
    return htmlBody;
  }


  public void setHtmlBody(String htmlBody) {
    this.htmlBody = htmlBody;
  }


  public EmailNotificationType emailAddressTo(List<String> emailAddressTo) {
    
    this.emailAddressTo = emailAddressTo;
    return this;
  }

  public EmailNotificationType addEmailAddressToItem(String emailAddressToItem) {
    if (this.emailAddressTo == null) {
      this.emailAddressTo = new ArrayList<>();
    }
    this.emailAddressTo.add(emailAddressToItem);
    return this;
  }

   /**
   * &#39;To&#39; recipients of the email
   * @return emailAddressTo
  **/
  @jakarta.annotation.Nonnull
  public List<String> getEmailAddressTo() {
    return emailAddressTo;
  }


  public void setEmailAddressTo(List<String> emailAddressTo) {
    this.emailAddressTo = emailAddressTo;
  }


  public EmailNotificationType emailAddressCc(List<String> emailAddressCc) {
    
    this.emailAddressCc = emailAddressCc;
    return this;
  }

  public EmailNotificationType addEmailAddressCcItem(String emailAddressCcItem) {
    if (this.emailAddressCc == null) {
      this.emailAddressCc = new ArrayList<>();
    }
    this.emailAddressCc.add(emailAddressCcItem);
    return this;
  }

   /**
   * &#39;Cc&#39; recipients of the email
   * @return emailAddressCc
  **/
  @jakarta.annotation.Nullable
  public List<String> getEmailAddressCc() {
    return emailAddressCc;
  }


  public void setEmailAddressCc(List<String> emailAddressCc) {
    this.emailAddressCc = emailAddressCc;
  }


  public EmailNotificationType emailAddressBcc(List<String> emailAddressBcc) {
    
    this.emailAddressBcc = emailAddressBcc;
    return this;
  }

  public EmailNotificationType addEmailAddressBccItem(String emailAddressBccItem) {
    if (this.emailAddressBcc == null) {
      this.emailAddressBcc = new ArrayList<>();
    }
    this.emailAddressBcc.add(emailAddressBccItem);
    return this;
  }

   /**
   * &#39;Bcc&#39; recipients of the email
   * @return emailAddressBcc
  **/
  @jakarta.annotation.Nullable
  public List<String> getEmailAddressBcc() {
    return emailAddressBcc;
  }


  public void setEmailAddressBcc(List<String> emailAddressBcc) {
    this.emailAddressBcc = emailAddressBcc;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailNotificationType emailNotificationType = (EmailNotificationType) o;
    return Objects.equals(this.type, emailNotificationType.type) &&
        Objects.equals(this.subject, emailNotificationType.subject) &&
        Objects.equals(this.plainTextBody, emailNotificationType.plainTextBody) &&
        Objects.equals(this.htmlBody, emailNotificationType.htmlBody) &&
        Objects.equals(this.emailAddressTo, emailNotificationType.emailAddressTo) &&
        Objects.equals(this.emailAddressCc, emailNotificationType.emailAddressCc) &&
        Objects.equals(this.emailAddressBcc, emailNotificationType.emailAddressBcc);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, subject, plainTextBody, htmlBody, emailAddressTo, emailAddressCc, emailAddressBcc);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailNotificationType {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    plainTextBody: ").append(toIndentedString(plainTextBody)).append("\n");
    sb.append("    htmlBody: ").append(toIndentedString(htmlBody)).append("\n");
    sb.append("    emailAddressTo: ").append(toIndentedString(emailAddressTo)).append("\n");
    sb.append("    emailAddressCc: ").append(toIndentedString(emailAddressCc)).append("\n");
    sb.append("    emailAddressBcc: ").append(toIndentedString(emailAddressBcc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("subject");
    openapiFields.add("plainTextBody");
    openapiFields.add("htmlBody");
    openapiFields.add("emailAddressTo");
    openapiFields.add("emailAddressCc");
    openapiFields.add("emailAddressBcc");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("subject");
    openapiRequiredFields.add("plainTextBody");
    openapiRequiredFields.add("emailAddressTo");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EmailNotificationType
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EmailNotificationType.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmailNotificationType is not found in the empty JSON string", EmailNotificationType.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EmailNotificationType.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if (!jsonObj.get("plainTextBody").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `plainTextBody` to be a primitive type in the JSON string but got `%s`", jsonObj.get("plainTextBody").toString()));
      }
      if ((jsonObj.get("htmlBody") != null && !jsonObj.get("htmlBody").isJsonNull()) && !jsonObj.get("htmlBody").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `htmlBody` to be a primitive type in the JSON string but got `%s`", jsonObj.get("htmlBody").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("emailAddressTo") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("emailAddressTo").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `emailAddressTo` to be an array in the JSON string but got `%s`", jsonObj.get("emailAddressTo").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("emailAddressCc") != null && !jsonObj.get("emailAddressCc").isJsonNull() && !jsonObj.get("emailAddressCc").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `emailAddressCc` to be an array in the JSON string but got `%s`", jsonObj.get("emailAddressCc").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("emailAddressBcc") != null && !jsonObj.get("emailAddressBcc").isJsonNull() && !jsonObj.get("emailAddressBcc").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `emailAddressBcc` to be an array in the JSON string but got `%s`", jsonObj.get("emailAddressBcc").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmailNotificationType.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmailNotificationType' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmailNotificationType> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmailNotificationType.class));

       return (TypeAdapter<T>) new TypeAdapter<EmailNotificationType>() {
           @Override
           public void write(JsonWriter out, EmailNotificationType value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmailNotificationType read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EmailNotificationType given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EmailNotificationType
  * @throws IOException if the JSON string is invalid with respect to EmailNotificationType
  */
  public static EmailNotificationType fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmailNotificationType.class);
  }

 /**
  * Convert an instance of EmailNotificationType to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
