/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.notifications.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.notifications.JSON;

/**
 * Holds readonly information about a Webhook notification
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WebhookNotificationTypeResponse {
  /**
   * The type of delivery mechanism for this notification
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    WEBHOOK("Webhook");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_HTTP_METHOD = "httpMethod";
  @SerializedName(SERIALIZED_NAME_HTTP_METHOD)
  private String httpMethod;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_AUTHENTICATION_TYPE = "authenticationType";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_TYPE)
  private String authenticationType;

  public static final String SERIALIZED_NAME_AUTHENTICATION_CONFIGURATION_ITEM_PATHS = "authenticationConfigurationItemPaths";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_CONFIGURATION_ITEM_PATHS)
  private Map<String, String> authenticationConfigurationItemPaths;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "contentType";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private String contentType;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private Object content = null;

  public WebhookNotificationTypeResponse() {
  }

  public WebhookNotificationTypeResponse type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of delivery mechanism for this notification
   * @return type
  **/
  @jakarta.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public WebhookNotificationTypeResponse httpMethod(String httpMethod) {
    
    this.httpMethod = httpMethod;
    return this;
  }

   /**
   * The HTTP method such as GET, POST, etc. to use on the request
   * @return httpMethod
  **/
  @jakarta.annotation.Nullable
  public String getHttpMethod() {
    return httpMethod;
  }


  public void setHttpMethod(String httpMethod) {
    this.httpMethod = httpMethod;
  }


  public WebhookNotificationTypeResponse url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The URL to send the request to
   * @return url
  **/
  @jakarta.annotation.Nullable
  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public WebhookNotificationTypeResponse authenticationType(String authenticationType) {
    
    this.authenticationType = authenticationType;
    return this;
  }

   /**
   * The type of authentication to use on the request
   * @return authenticationType
  **/
  @jakarta.annotation.Nullable
  public String getAuthenticationType() {
    return authenticationType;
  }


  public void setAuthenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
  }


  public WebhookNotificationTypeResponse authenticationConfigurationItemPaths(Map<String, String> authenticationConfigurationItemPaths) {
    
    this.authenticationConfigurationItemPaths = authenticationConfigurationItemPaths;
    return this;
  }

  public WebhookNotificationTypeResponse putAuthenticationConfigurationItemPathsItem(String key, String authenticationConfigurationItemPathsItem) {
    if (this.authenticationConfigurationItemPaths == null) {
      this.authenticationConfigurationItemPaths = new HashMap<>();
    }
    this.authenticationConfigurationItemPaths.put(key, authenticationConfigurationItemPathsItem);
    return this;
  }

   /**
   * The paths of the Configuration Store configuration items that contain the authentication configuration. Each  authentication type requires different keys:  - Lusid - None required  - BasicAuth - Requires &#39;Username&#39; and &#39;Password&#39;  - BearerToken - Requires &#39;BearerToken&#39; and optionally &#39;BearerScheme&#39;     e.g. the following would be valid assuming that the config is present in the configuration store at the  specified paths:      \&quot;authenticationType\&quot;: \&quot;BasicAuth\&quot;,   \&quot;authenticationConfigurationItemPaths\&quot;: {   \&quot;Username\&quot;: \&quot;config://personal/myUserId/WebhookConfigurations/ExampleService/AdminUser\&quot;,   \&quot;Password\&quot;: \&quot;config://personal/myUserId/WebhookConfigurations/ExampleService/AdminPassword\&quot;   }
   * @return authenticationConfigurationItemPaths
  **/
  @jakarta.annotation.Nullable
  public Map<String, String> getAuthenticationConfigurationItemPaths() {
    return authenticationConfigurationItemPaths;
  }


  public void setAuthenticationConfigurationItemPaths(Map<String, String> authenticationConfigurationItemPaths) {
    this.authenticationConfigurationItemPaths = authenticationConfigurationItemPaths;
  }


  public WebhookNotificationTypeResponse contentType(String contentType) {
    
    this.contentType = contentType;
    return this;
  }

   /**
   * The type of the content e.g. Json
   * @return contentType
  **/
  @jakarta.annotation.Nullable
  public String getContentType() {
    return contentType;
  }


  public void setContentType(String contentType) {
    this.contentType = contentType;
  }


  public WebhookNotificationTypeResponse content(Object content) {
    
    this.content = content;
    return this;
  }

   /**
   * The content of the request
   * @return content
  **/
  @jakarta.annotation.Nullable
  public Object getContent() {
    return content;
  }


  public void setContent(Object content) {
    this.content = content;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookNotificationTypeResponse webhookNotificationTypeResponse = (WebhookNotificationTypeResponse) o;
    return Objects.equals(this.type, webhookNotificationTypeResponse.type) &&
        Objects.equals(this.httpMethod, webhookNotificationTypeResponse.httpMethod) &&
        Objects.equals(this.url, webhookNotificationTypeResponse.url) &&
        Objects.equals(this.authenticationType, webhookNotificationTypeResponse.authenticationType) &&
        Objects.equals(this.authenticationConfigurationItemPaths, webhookNotificationTypeResponse.authenticationConfigurationItemPaths) &&
        Objects.equals(this.contentType, webhookNotificationTypeResponse.contentType) &&
        Objects.equals(this.content, webhookNotificationTypeResponse.content);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, httpMethod, url, authenticationType, authenticationConfigurationItemPaths, contentType, content);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookNotificationTypeResponse {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    httpMethod: ").append(toIndentedString(httpMethod)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    authenticationType: ").append(toIndentedString(authenticationType)).append("\n");
    sb.append("    authenticationConfigurationItemPaths: ").append(toIndentedString(authenticationConfigurationItemPaths)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("httpMethod");
    openapiFields.add("url");
    openapiFields.add("authenticationType");
    openapiFields.add("authenticationConfigurationItemPaths");
    openapiFields.add("contentType");
    openapiFields.add("content");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WebhookNotificationTypeResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookNotificationTypeResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookNotificationTypeResponse is not found in the empty JSON string", WebhookNotificationTypeResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("httpMethod") != null && !jsonObj.get("httpMethod").isJsonNull()) && !jsonObj.get("httpMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `httpMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("httpMethod").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("authenticationType") != null && !jsonObj.get("authenticationType").isJsonNull()) && !jsonObj.get("authenticationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authenticationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authenticationType").toString()));
      }
      if ((jsonObj.get("contentType") != null && !jsonObj.get("contentType").isJsonNull()) && !jsonObj.get("contentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `contentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookNotificationTypeResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookNotificationTypeResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookNotificationTypeResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookNotificationTypeResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookNotificationTypeResponse>() {
           @Override
           public void write(JsonWriter out, WebhookNotificationTypeResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookNotificationTypeResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WebhookNotificationTypeResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WebhookNotificationTypeResponse
  * @throws IOException if the JSON string is invalid with respect to WebhookNotificationTypeResponse
  */
  public static WebhookNotificationTypeResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookNotificationTypeResponse.class);
  }

 /**
  * Convert an instance of WebhookNotificationTypeResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
